more die-fast error handling

diff --git a/docker/hooks/build b/docker/hooks/build
--- a/docker/hooks/build
+++ b/docker/hooks/build
@@ -62,8 +62,8 @@ main() {
     now="$(date --utc +%FT%TZ)"
     echo "Current timestamp: ${now}" ; echo
 
+    ### no quotes around ${params}!
     set -x
-    ### no quotes around 'params'
     docker build ${params} \
         -f "${DOCKERFILE_PATH}" \
             --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -93,7 +93,11 @@ main() {
             ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
             \
         -t "${DOCKER_REPO}:${DOCKER_TAG}${target_stage:+_${target_stage}}" "${_build_context}"
+
+    exit_code=$?
     set +x
+    
+    if [[ ${exit_code} -ne 0 ]] ; then die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}'" ${exit_code} ; fi
 }
 
 main $@
diff --git a/docker/hooks/pre_build b/docker/hooks/pre_build
--- a/docker/hooks/pre_build
+++ b/docker/hooks/pre_build
@@ -57,8 +57,9 @@ main() {
     fi
 
     ### build a temporary helper image for getting the current version sticker values
+
+    ### no quotes around ${params}!
     set -x
-    ### no quotes around 'params'
     docker build ${params} \
         -f "${DOCKERFILE_PATH}" \
             --build-arg BASEIMAGE="${BASEIMAGE}" \
@@ -84,7 +85,11 @@ main() {
             ${FEATURES_FIREFOX_PLUS:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_firefox_plus"} \
             \
         -t "${DOCKER_REPO}":"${DOCKER_TAG}${helper_suffix}" "${_build_context}"
+
+    exit_code=$?
     set +x
+
+    if [[ ${exit_code} -ne 0 ]] ; then set +x; die "Failed to build image '${DOCKER_REPO}:${DOCKER_TAG}${helper_suffix}'" ${exit_code} ; fi
 
     ### get the actual verbose version sticker value from the helper image and store it as the current one
     ### note that some apps require display to report their versions correctly (e.g. Ristretto or Screenshooter)
diff --git a/docker/hooks/push b/docker/hooks/push
--- a/docker/hooks/push
+++ b/docker/hooks/push
@@ -12,6 +12,7 @@ deployment_push() {
     local target
     local repo="${_deploy_repo##*/}"
     local keeper_repo_tag="${_deploy_builder_tags[0]}"
+    local -i exit_code=0
 
     if [[ -n "${repo}" && "${repo}" != "${_prohibited_repo_name}" ]] ; then
 
@@ -27,7 +28,13 @@ deployment_push() {
                 echo ; echo "Deploying image '${target}'"
                 docker tag "${DOCKER_REPO}:${keeper_repo_tag}" "${target}"
                 docker push "${target}"
+                exit_code=$?
                 docker rmi "${target}"
+
+                if [[ ${exit_code} -ne 0 ]] ; then
+                    docker logout
+                    die "Unable to push image '${target}'" ${exit_code}
+                fi
             fi
         done
 
@@ -40,6 +47,7 @@ main() {
     local target
     local repo="${DOCKER_REPO##*/}"
     local keeper_repo_tag="${_deploy_builder_tags[0]}"
+    local -i exit_code=0
 
     if [[ -f "${_build_context}/${_scrap_demand_stop_building}" ]] ; then
         echo "Skipping push on demand."
@@ -78,13 +86,24 @@ main() {
 
                     # first element is the master repo (a keeper)
                     docker push "${DOCKER_REPO}:${t}"
+                    exit_code=$?
 
+                    if [[ ${exit_code} -ne 0 ]] ; then
+                        docker logout
+                        die "Unable to push image '${DOCKER_REPO}:${t}'" ${exit_code}
+                    fi
                 else
                     target="${DOCKER_REPO}:${t}"
 
                     docker tag "${DOCKER_REPO}:${keeper_repo_tag}" "${target}"
                     docker push "${target}"
+                    exit_code=$?
                     docker rmi "${target}"
+
+                    if [[ ${exit_code} -ne 0 ]] ; then
+                        docker logout
+                        die "Unable to push image '${target}'" ${exit_code}
+                    fi
                 fi
             done
 
