first G3v2 milestone release

diff --git a/docker/hooks/build b/docker/hooks/build
--- a/docker/hooks/build
+++ b/docker/hooks/build
@@ -1,20 +1,31 @@
 #!/bin/bash -e
 
+echo -e "\n==> EXECUTING @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
+
 declare _mydir=$(dirname $0)
 source "${_mydir}"/env.rc
 source "${_mydir}"/util.rc
 
 main() {
+    local now
+    local version_sticker
+    local cache_script="cache"
+    local -i exit_code=0
 
-    if [ -f "${_build_context}/${_scrap_demand_stop_building}" ] ; then
+    if [[ -f "${_build_context}/${_scrap_demand_stop_building}" ]] ; then
+    
         echo "Skipping build on demand."
         return 0
     fi
 
-    local now
-    local version_sticker
+    ### refresh local cache for the case the 'pre_build' was not run
+    "${_mydir}/${cache_script}" "${_branch}" "${_blend}"
+    exit_code=$?
+    if [[ ${exit_code} -ne 0 ]] ; then die "Script '${cache_script}' failed with code ${exit_code}." ${exit_code} ; fi
 
-    if [ -f "${_build_context}/${_scrap_version_sticker_current}" ] ; then
+    ### get current version sticker
+    if [[ -f "${_build_context}/${_scrap_version_sticker_current}" ]] ; then
+
         version_sticker="$( cat ${_build_context}/${_scrap_version_sticker_current} )"
     else
         version_sticker="null"
@@ -39,8 +50,14 @@ main() {
             ${FEATURES_THUMBNAILING:+--build-arg ARG_FEATURES_THUMBNAILING=1} \
             ${FEATURES_USER_GROUP_OVERRIDE:+--build-arg ARG_FEATURES_USER_GROUP_OVERRIDE=1} \
             \
+            ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_DISTRO=${TIGERVNC_DISTRO}} \
+            ${FEATURES_VNC:+--build-arg ARG_TIGERVNC_VERSION=${TIGERVNC_VERSION}} \
+            \
+            ${FEATURES_NOVNC:+--build-arg ARG_NOVNC_VERSION=${NOVNC_VERSION}} \
+            ${FEATURES_NOVNC:+--build-arg ARG_WEBSOCKIFY_VERSION=${WEBSOCKIFY_VERSION}} \
             ${FEATURES_NOVNC:+--build-arg ARG_MERGE_STAGE_VNC_BASE="stage_novnc"} \
             \
+            ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_DISTRO=${CHROMIUM_DISTRO}} \
             ${FEATURES_CHROMIUM:+--build-arg ARG_CHROMIUM_VERSION=${CHROMIUM_VERSION}} \
             ${FEATURES_CHROMIUM:+--build-arg ARG_MERGE_STAGE_BROWSER_BASE="stage_chromium"} \
             \
@@ -52,3 +69,5 @@ main() {
 }
 
 main $@
+
+echo -e "\n==> FINISHED  @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
diff --git a/docker/hooks/push b/docker/hooks/push
--- a/docker/hooks/push
+++ b/docker/hooks/push
@@ -1,69 +1,85 @@
 #!/bin/bash -e
 ### @accetto, August 2021
 
+echo -e "\n==> EXECUTING @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
+
 declare _mydir=$(dirname $0)
 source "${_mydir}"/env.rc
 source "${_mydir}"/util.rc
 
-builder_push() {
-
-    echo ; echo "Pushing builder image ${DOCKER_REPO}:${DOCKER_TAG}"
-    docker push ${DOCKER_REPO}:${DOCKER_TAG}
-}
-
 deployment_push() {
     local target
+    local repo="${_deploy_repo##*/}"
 
-    ### push all target tags into the deployment repository
-    for t in "${_deploy_tags[@]}" ; do
+    if [[ -n "${repo}" && "${repo}" != "${_prohibited_repo_name}" ]] ; then
 
-        ### note that the builder and deployment repositories could be identical
-        ### in that case skip the tag which has been already published above
-        if [ "${DOCKER_REPO}" != "${_deploy_repo}" ] || [ "${DOCKER_TAG}" != "${t}" ] ; then
+        ### push all target tags into the deployment repository
+        for t in "${_deploy_tags[@]}" ; do
 
-            target="${_deploy_repo}:${t}"
+            ### note that the builder and deployment repositories could be identical
+            ### in that case skip the tag which has been already published above
+            if [[ "${DOCKER_REPO}" != "${_deploy_repo}" || "${DOCKER_TAG}" != "${t}" ]] ; then
 
-            echo ; echo "Deploying image '${target}'"
-            docker tag "${DOCKER_REPO}:${DOCKER_TAG}" "${target}"
-            docker push "${target}"
-        fi
-    done
+                target="${_deploy_repo}:${t}"
+
+                echo ; echo "Deploying image '${target}'"
+                docker tag "${DOCKER_REPO}:${DOCKER_TAG}" "${target}"
+                docker push "${target}"
+            fi
+        done
+
+    else
+        echo "Skipping push because of null or prohibited deployment repository '${repo}'."
+    fi
 }
 
 main() {
     local target
+    local repo="${DOCKER_REPO##*/}"
 
-    if [ -f "${_build_context}/${_scrap_demand_stop_building}" ] ; then
+    if [[ -f "${_build_context}/${_scrap_demand_stop_building}" ]] ; then
         echo "Skipping push on demand."
         return 0
     fi
 
-    # DEPRECATED: This if block is deprecated and it will be replaced.
-    if [ "${_stage}" == "local" ] ; then
-        if [ -n "${DOCKERHUB_USERNAME}" ] && [ -n "${DOCKERHUB_PASSWORD}" ] ; then
+    ### Docker Hub log-in
+    if [[ -n "${DOCKERHUB_USERNAME}" && -n "${DOCKERHUB_PASSWORD}" ]] ; then
 
-            echo "Logging-in on Docker Hub..."
-            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
-            if [ ! $? ] ; then
-                echo "Docker Hub login failed"
-                return 1
-            fi
-        else
-            echo "Local pushing requires Docker Hub login."
-            echo "However, your environment does not provide required authentication data."
+        echo "Logging-in on Docker Hub"
+        echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
+
+        if [[ ! $? ]] ; then
+        
+            echo "Docker Hub login failed"
             return 1
         fi
+
+    else
+        echo "Push requires Docker Hub login."
+        echo "However, your environment does not provide required authentication data."
+        return 1
     fi
 
-    # DEPRECATED: This if block is deprecated and it will be replaced.
-    ### push image into the builder repository
-    if [ "${_stage}" != "local" ] ; then builder_push ; fi
+    ### push images into the builder repository
+    if [[ "${FORCE_PUBLISHING_BUILDER_REPO}" == "1" ]] ; then
+
+        if [[ -n "${repo}" && "${repo}" != "${_prohibited_repo_name}" ]] ; then
+
+            echo ; echo "Pushing builder image ${DOCKER_REPO}:${DOCKER_TAG}"
+            docker push ${DOCKER_REPO}:${DOCKER_TAG}
+
+        else
+            echo "Skipping forced push because of null or prohibited builder repository '${repo}'."
+        fi
+    fi
 
     ### push images into the deployment repository
     deployment_push
 
-    # DEPRECATED: This if block is deprecated and it will be replaced.
-    if [ "${_stage}" == "local" ] ; then docker logout ; fi
+    ### Docker Hub log-out
+    docker logout
 }
 
 main $@
+
+echo -e "\n==> FINISHED  @$(date -u +'%Y-%m-%d_%H-%M-%S'): ${0} $@\n"
